# Generated by Django 4.2.4 on 2023-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='productImages')),
                ('sale_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('time_gram', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
